# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jk1DgDnd5gM-WmQavGAaPb6w_mGYzReN
"""

#1
number1 = int(input("정수를 입럭하시오"))
number2 = int(input("정수를 입럭하시오"))
number3 = int(input("정수를 입럭하시오"))
if number1 != 0:
  print(sorted([number1, number2, number3],reverse=True))
else:
  print("종료합니다.")

#2
chk_plus = 0
chk_minus = 0
chk_2 = 0
chk_1 = 0
for i in range(10):
  number = int(input("정수 입력"))
  if number > 0 :
    chk_plus += 1
    if (number % 2)==0 :
      chk_2 += 1
    else :
      chk_1 += 1
  if number < 0 :
    chk_minus += 1
    
print("양수 : {0:2d}, 음수 : {1:2d}, 짝수 : {2:2d}, 홀수 : {3:2d}".format(chk_plus, chk_minus, chk_2, chk_1))

#3
sum35 = 0
for i in range(3,1001, 3) :
    sum3 += i
    print(i, end = ' ')
    if (i % 30) == 0:
      print('\n')
print('\n')
for i in range(5,1001, 5) :
    sum5 += i
    print(i, end = ' ')
    if (i % 50) == 0:
      print('\n')
print('\n')
for i in range(1, 1001):
  if ((i % 3) == 0) or ((i % 5) == 0):
    sum35 += i
print("3의 배수이면서 5의 배수의 합 :  {0:d}".format(sum35))

#4
number = int(input("정수를 입력하시오"))
if number!=0:
  for i in range(1, 10):
    print("{0:d} * {1:d} = {2:d}".format(number, i, number*i), end = '\n')
else:
  print("종료합니다")

#5
for i in range(10):
  number[i] = int(input("정수를 입력하시오"))
print(max(number.values()))