# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v6K4C-vnvyIQ8WiaaH8g5m-R_odlv4bS
"""

#1
def my_join(str1, str2):
  str = str1 + str2
  return str

my_join('aaa','bbb')

#2
def my_split(str, ch):
  #값, 리스트 초기화
  i=0
  fd = ''
  my_list=[]
  final_list=[]
  
  while True:
    fd = str.find(ch)
    if fd < 0:
      my_list.append(str[:])
      break
    my_list.append(str[0:fd])
    final_list.append( str[fd+len(ch):] )
    str = final_list[i]
    i += 1

  return my_list
  
my_split('아들어 너는 계획이 있구나','계획')

##6일차
#1
def my_max(number):
  max_number = number[0]
  for i in range(1, len(number)):
    if max_number < number[i]:
      max_number = number[i]
    else :
      continue
  return max_number
  
my_max([1,2,3,7,5,6,100,555,55,44,3])

#2
def my_min(number):
  min_number = number[0]
  for i in range(1, len(number)):
    if min_number > number[i]:
      min_number = number[i]
    else:
      continue;
  return min_number

my_min([1,2,6,2,5,6])

#3
def my_sum(number):
  sum_number=0
  for i in range(len(number)):
    sum_number += int(number[i])
  return sum_number

my_sum([1,3,3,4,5,6])

#4
def my_avg(number):
  sum_number=0
  avg_number = 0
  for i in range(len(number)):
    sum_number += int(number[i])
  avg_number = sum_number/len(number)
  return avg_number

my_avg([1,2,3,4,5,6])

def my_split(str1, ch):

    if b in a:
      c = a.index(b)
      d = a[ : c] + '\n' +a[c : ]
      e = list(d)
    else:
      print("error")
    return e


a = input('문장을 입력하세요: ')
b = input('단어를 입력하세요: ')
f = my_split(a, b)


print(f)