# -*- coding: utf-8 -*-
"""Exam8_class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ctLDg_MzwsPaOGlIp2orKmabc0CP4c7-
"""

class Student:
  def __init__(self, name = None,
                     sub1 = None,
                     sub2 = None,
                     sub3 = None,
                     sum_grade = None,
                     avg_grade = None,
                     result = None):
    self.name = name
    self.sub1 = sub1
    self.sub2 = sub2
    self.sub3 = sub3
    self.sum_grade = sum_grade
    self.avg_grade = avg_grade
    self.result = result

  def inputData(self):
    i = 0
    total_name=[]
    total_sub1=[]
    total_sub2=[]
    total_sub3=[]
    total_sum_grade=[]
    total_avg_grade=[]
    total_result=[]
    
    self.name = input("이름을 입력하시오. ( end  : 종료 )  : ")
    while i < 10 and self.name != 'end':
      self.sub1 = int(input("1과목 성적을 입력하시오."))
      self.sub2 = int(input("2과목 성적을 입력하시오."))
      self.sub3 = int(input("3과목 성적을 입력하시오."))
      self.sub_grade = self.setSum_grade()
      self.avg_grade = self.setAvg_grade()
      self.result = self.setResult()
      
      #total.append([self.name, self.sub1, self.sub2, self.sub3,
      #                self.sub_grade, self.avg_grade, self.result])
      
      total_name.append(self.name)
      total_sub1.append(self.sub1)
      total_sub2.append(self.sub2)
      total_sub3.append(self.sub3)
      total_sum_grade.append(self.sum_grade)
      total_avg_grade.append(self.avg_grade)
      total_result.append(self.result)
                       
      self.name = input("이름을 입력하시오. ( end  : 종료 )  : ")
      i += 1
    self.printStudentInfo(total_name, total_sub1, total_sub2, total_sub3,
                         total_sum_grade, total_avg_grade, total_result)
    
  def setSum_grade(self):
    self.sum_grade = self.sub1 + self.sub2 + self.sub3
    return self.sum_grade
  
  def setAvg_grade(self):
    self.avg_grade = (self.sub1 + self.sub2 + self.sub3)/3
    return self.avg_grade
  
  def setResult(self):
    if self.avg_grade >= 90 :
      self.result = "Excellent"
    elif self.avg_grade <= 60:
      self.result = "Fail"
    else:
      self.result = ""
    return self.result
  
  def getName(self):
    return self.name
  
  def getSub1(self):
    return self.sub1
  
  def getSub2(self):
    return self.sub2
  
  def getSub3(self):
    return self.sub3

  def printStudentInfo(self, total_name, total_sub1, total_sub2, total_sub3,
                         total_sum_grade, total_avg_grade, total_result):
    print()
    print("==============================================================")
    for i in range(len(total_name)):
      print('{0:<10} {1} {2} {3} {4} {5:>3.1f} {6:<}'.format(total_name[i], total_sub1[i],
                                                          total_sub2[i], total_sub3[i],
                                                          total_sum_grade[i], total_avg_grade[i],
                                                          total_result[i]))
    print("==============================================================")
  
if __name__ == '__main__':
  student = Student()
  student.inputData()
  student.printStudentInfo()