# -*- coding: utf-8 -*-
"""Person.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q8IGlVKy7uMXL3BftvjlESjphwxROfvH
"""

'''
  Person.py

  최대 50명 사람의 이름, 전화번호, 이메일 정보를 기록하는 전화번호부를 컴퓨터로 관리하고자 한다.
  
  개인 정보 : member(attribute) - 이름(name), 전화번호(tel), 이메일(email)
  (Person)    method(behavior)  - 이름을 기록한다.      - setName()
                                  이름을 읽는다.        - getName()
                                  전화번호를 기록한다.  - setTel()
                                  전화번호를 읽는다.    - getTel()
                                  이메일을 기록한다.    - setEmail()
                                  이메일을 읽는다.      - getEmail()
                                  개인정보를 기록한다.  - writePersonInfo()
                                  개인정보를 읽는다.    - readPersonInfo()
'''
class Person:
  def __init__(self, name=None,
                     tel=None,
                     email=None): # 생성자 ( Constructor )
    self.name = name              # instance 생성시 자동으로 호출되는 Method
    self.tel = tel
    self.email = email
  
  def __del__(self):              # 소멸자 ( Destructor ) , self 인자만 씀. 잘 안씀.
    print( '{0} Good Bye...^^'.format(self.__dir__))  # 메모리 주소(reference가 표시됨)
                                  # instance가 메모리에서 소멸될 때 자동
                                  # 호출되는 Method
      
  def setName(self, name):
    self.name = name
    
  def getName(self):
    return self.name
  
  def setTel(self, tel):
    self.tel = tel
  
  def getTel(self):
    return self.tel
  
  def setEmail(self, email):
    self.email = email
    
  def getEmail(self):
    return self.email
  
  def writePersonInfo(self, name, tel, email):
    self.name = name
    self.tel = tel
    self.email = email
    
  def readPersonInfo(self):
    return self.name, self.tel, self.email
  
if __name__ == '__main__':
  person = Person()
  print('Name  : {0}'.format(person.getName()))
  print('Tel   : {0}'.format(person.getTel()))
  print('Email : {0} \n'.format(person.getEmail()))

  person.setName('Hong')
  person.setTel('010-1234-5678')
  person.setEmail('Hong@korea.com')
  print('Name  : {0}'.format(person.getName()))
  print('Tel   : {0}'.format(person.getTel()))
  print('Email : {0} \n'.format(person.getEmail()))
  
  person2 = Person( 'Kim', '010-2345-6789', 'Kim@korea.com')
  print('Name  : {0}'.format(person2.getName()))
  print('Tel   : {0}'.format(person2.getTel()))
  print('Email : {0} \n'.format(person2.getEmail()))
  
  person3 = Person( 'Kim', '010-2345-6789')
  print('Name  : {0}'.format(person3.getName()))
  print('Tel   : {0}'.format(person3.getTel()))
  print('Email : {0} \n'.format(person3.getEmail()))
  
  person4 = Person( 'Kim')
  print('Name  : {0}'.format(person4.getName()))
  print('Tel   : {0}'.format(person4.getTel()))
  print('Email : {0} \n'.format(person4.getEmail()))

