# -*- coding: utf-8 -*-
"""Person.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q8IGlVKy7uMXL3BftvjlESjphwxROfvH
"""

'''
  Person.py

  최대 50명 사람의 이름, 전화번호, 이메일 정보를 기록하는 전화번호부를 컴퓨터로 관리하고자 한다.
  
  개인 정보 : member(attribute) - 이름(name), 전화번호(tel), 이메일(email)
  (Person)    method(behavior)  - 이름을 기록한다.      - setName()
                                  이름을 읽는다.        - getName()
                                  전화번호를 기록한다.  - setTel()
                                  전화번호를 읽는다.    - getTel()
                                  이메일을 기록한다.    - setEmail()
                                  이메일을 읽는다.      - getEmail()
                                  개인정보를 기록한다.  - writePersonInfo()
                                  개인정보를 읽는다.    - readPersonInfo()
'''
class Person:                     # Entity Class ( Data 성격 )
  def __init__(self, name,
                     tel,
                     email=''): #name과 tel은 필수로 입력해야한다.
    self.name = name
    self.tel = tel
    self.email = email
       
  def getName(self):
    return self.name
  
  def getTel(self):
    return self.tel
  
  def getEmail(self):
    return self.email
  
  def writePersonInfo(self, name, tel, email):
    self.name = name
    self.tel = tel
    self.email = email
    
  def readPersonInfo(self):
    return self.name, self.tel, self.email
  
  def __repr__( self ):
      str = '{0:10} {1:<13} {2:<30}'.format( self.name, self.tel, self.email)
      return str

class TelephoneBook:
    MAX = 50
    count_person = 0

    def __init__( self ):
        self.telephoneBook = {}

    def writePersonInfo( self, name, tel, email = ''):
        self.telephoneBook[ name ] = Person( name, tel, email )
        TelephoneBook.count_person += 1

    def readPersonInfo( self, key):
        return self.telephoneBook[ key ].readPersonInfo()

    def printTelephoneBook(self):
        for key in self.telephoneBook:
            print(self.telephoneBook[key])

    def __repr__( self ):
        s = []
        for key in self.telephoneBook:
            s.append(self.telephoneBook[ key ])
        return str(s)

def testMain():
    telephoneBook = TelephoneBook()

    telephoneBook.writePersonInfo('Hong', '010-1234-5678', 'Hong@korea.com')
    telephoneBook.writePersonInfo('Kim', '010-5678-1234', email='')
    telephoneBook.writePersonInfo('Lee', '010-2468-1357', 'Lee@korea.com')

    telephoneBookAll = str( telephoneBook )
    for v in telephoneBookAll:
        print( v, end ='' )

    print()
    telephoneBook.printTelephoneBook()

    name = input( 'input name : ')
    tel = input('input tel : ')
    email = input('input email : ')
    telephoneBook.writePersonInfo( name, tel, email )
    telephoneBook.printTelephoneBook()
    
if __name__ == '__main__':
    testMain()